from .test_assignment import *
from .test_block_statements import *
from .test_cmd_print_statements import *
from .test_empty_statements import *
from .test_equality import *
from .test_func_declaration import *
from .test_if_statement import *
from .test_literals import *
from .test_logic import *
from .test_loops import *
from .test_math import *
from .test_relationals import *
from .test_statement_list import *
from .test_unary import *
from .test_variables import *